language: python
python:
  - "2.7"
  - "3.4"
git:
  submodules: false
branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/  # allows building version tags
sudo: false  # Enables running on faster infrastructure.
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - enchant
install:
  - pip install -r requirements.txt -r dev-requirements.txt
  - pip install coveralls
  - pip install flake8
script:
  - ./checkstyle.sh
  - coverage run --source sopel -m py.test -v .
  - coverage report --show-missing
after_success:
  coveralls
